### ISSUE TITLE
Help to make an yii2 vue2 dropzone extension

### ISSUE THREAD

**Issue by VenuNarukulla** [antkaz/yii2-vue#1]
This is  @superb.

Is it possible to make yii2 extension from `https://rowanwins.github.io/vue-dropzone/docs/dist/index.html#/installation` 

How to handle that export and other stuff?

**Comment by antkaz** [comment]
Hmmmm.... I tried to use this extension without a webpack (i.e., as a CDN), but I did not succeed. Do you have an example?
