### ISSUE TITLE
how to handle a Object/class from yii

### ISSUE THREAD

**Issue by skeeran** [antkaz/yii2-vue#2]
Hi,
can u explain me how to handle a Object that comes from Yii2 like
'userModel' => User::findOne(Yii::$app->user->id),

because for me its empty

Thanks

**Comment by antkaz** [comment]
try
'userModel' => User::findOne(\Yii::$app->user->id)

**Comment by skeeran** [comment]
print_r(\app\models\User::findOne(\Yii::$app->user->id));

the data is there when i pass it to vue like this 'userModel' => User::findOne(\Yii::$app->user->id)
then its empty 

![image](https://user-images.githubusercontent.com/7000138/40349899-4fb6218e-5da8-11e8-92c2-c2bb0f2504fc.png)

**Comment by antkaz** [comment]
Most likely, a bug in your code.

I passed the object to the view:
```php
public function actionAbout()
{
    return $this->render('about', [
        'user' => User::findIdentity(Yii::$app->user->getId())
    ]);
}
```
then passed this object to Vue in the view file:

```php
<?php \antkaz\vue\Vue::begin([
    'clientOptions' => [
        'data' => [
            'user' => $user
        ]
    ]
]) ?>

<?php antkaz\vue\Vue::end(); ?>
```
as a result, I get
![image](https://user-images.githubusercontent.com/19654261/40351053-e67dd410-5dc4-11e8-943f-f70d220b2bea.png)

**Comment by skeeran** [comment]
ohm mm this is strange when i print_r the userObject is there but on vue its empty

when i do like this  'userModel' => User::find()->where(['IdUser' => \Yii::$app->user->id])->asArray()->one(),
then it is working as Object it is not working :(

**Comment by skeeran** [comment]
oh was my mistake now working fine :D

**Comment by antkaz** [comment]
Good 👍 :-)

**Comment by skeeran** [comment]
it would be nice if u can upload more example code with difficult stuff or a sample project where u handle lot of things over  vue :D

**Comment by skeeran** [comment]
thank your for the help
