### ISSUE TITLE
how to add a component ?

### ISSUE THREAD

**Issue by skeeran** [antkaz/yii2-vue#3]
Hi,

how to add a component like [Vue-draggble](https://github.com/SortableJS/Vue.Draggable)

thank you for the help.

**Comment by antkaz** [comment]
Hi. 
VueDraggable + Google = https://jsfiddle.net/dede89/m2v0orcn/  

You need to add resources:
- Sortable.js
- vuedraggable.js

**Comment by skeeran** [comment]
Hi thank you for the replay,
my thought was where to add these ressources ? in your VueAsset.php ?
because when i add them ass a cdn in yii2 layout header part its is not working.

**Comment by antkaz** [comment]
No. In vueAsset you do not need to add.  
You need to add them to the AppAsset, and VueAsset as a dependency:

```php
<?php

namespace app\assets;

use yii\web\AssetBundle;

class AppAsset extends AssetBundle
{
    public $basePath = '@webroot';
    public $baseUrl = '@web';
   
    public $js = [
        'js/Sortable.js',
        'js/vuedraggable.js',
    ];
    public $depends = [
        \antkaz\vue\VueAsset::class
    ];
}
```

**Comment by skeeran** [comment]
thank you.

but isnt it better when such thing is done through your widget so then everything is in one place regarding vue ?

**Comment by antkaz** [comment]
VueDraggable is a separate component, which depends on the VueJs. But VueDraggable does not apply to it. Adding it to the widget is incorrect. It would be more correct to create a new widget and specify dependencies. As, for example, [here](https://github.com/antkaz/yii2-iview/blob/master/src/IViewAsset.php)

P.S. Sorry, I do not speak english well. I hope everything is clear to you :)
